Practice Sheet: Review how indexing changes as we move from Python lists, to pandas objects, to NumPy arrays. Then apply the core NumPy skills used in spatial computing.
Try the questions without running the code. Then create a JN.
Python indexing refresher

1.	What value is returned by locations[0]?
“Oak”
2.	What value is returned by locations[4]?
“Elm”
3.	What values are returned by locations[1:4]?
Pine, Maple, Cedar, Elm
4.	Write an indexing expression that returns "Maple".
locations[2]

5.	What does points[2] return?
[180,260]

6.	What does points[2][1] return? Explain what each index selects.
260

7.	Write an expression that returns the x-coordinate of the second point. Assume the coordinates are stored as [x,y].
Points[1][1]

pandas indexing refresher

8.	What type of object is returned by df["ft"]?
Panda series
9.	Write code to select the name and ft columns together.
Df[[“ft, “name”]]
10.	What row is returned by df.iloc[1]?
The second row 
11.	Write code using iloc to select the first three rows.
Df.iloc[0:4]
12.	Write code to select rows where ft is greater than 30.
mask = df[“ft”] > “30”
big_length = df[mask]
13.	What rows are returned by df.iloc[1:3]?          2nd and 3rd row

 
Moving to NumPy arrays

14.	What does points.shape return, and what do the two numbers mean?
It returns the number of rows then the number of columns, this would return (4,2)
15.	What does points[0] return?
Array([100, 200])
16.	What does points[0, 1] return?
Np.int64(200)
17.	What does points[:, 0] return? Explain the colon.
The first column, the colon means every row so every input from the first column would be printed: array([100, 140, 180, 120])
18.	What does points[:, 1] return?
The second column: array([200, 230, 260, 280])
19.	Write NumPy indexing code that returns the second and third rows.
Points[2:4]
20.	Compare points[2][1] with points[2, 1].         They return the same thing
Vectorized operations

21.	Without running the code, determine the result of points + shift.

It would add 10 to every number in the 1st column and 20 to every row in the 2nd column:
Array([[110, 220],
[150, 250],
[190, 280],
[130, 300]])
22.	Why does this operation not require a Python for loop?
NumPy applies the same operation to every row, this is called vectorization.

Boolean masks and spatial queries

23.	Write the Boolean values stored in inside[:].
Array([False, True, True, False
24.	What does points[inside] return?
Array([[140, 230],
[180, 260]])
25.	In GIS language, what spatial operation is this Boolean mask approximating?
 
np.where() and classification

26.	What values are stored in classes[:]?
[0, 1, 0, 1]
27.	In your own words, explain the three arguments in np.where(condition, value_if_true, value_if_false).
The condition is the variable being evaluated as true or false, in the previous question it was whether the elevation value was greater or equal to 500. The value_if_true is the value that is newly assigned if the condition is met, the value_if_false is the value that is newly assigned ig the condition is not met in the specified array.

Distance and pandas connection

28.	What does a - b return?
Array([-40, -30])
29.	Explain why this calculation is an example of vectorized arithmetic.
distance = np.sqrt(((a - b) ** 2).sum())
It is a vectorized arithmetic because it applies an equation to every value in an 
30.	What type of object is ft_array?
Numpy.adarray
31.	What happened to the pandas index and column label when the Series was converted to NumPy?
It was dropped, only the data values were kept.


Big picture
32.	Complete the table by describing what is being selected.

Structure	Expression	What it selects
Python list	locations[2]	The third value of a list
Nested Python list	points_list[2][1]	The second value of the second list of a larger list
pandas DataFrame	df.iloc[2, 1]	The third and second row of a df
NumPy array	points[2, 1]	The third row, second input of an array
NumPy array	points[:, 0]	The first column of an array

33.	In one sentence: what is the main indexing idea that stays the same across Python, pandas, and NumPy?

The first entry/row is always zero and increases with values


34.	What becomes easier when data are arranged as a 2-D NumPy array?
Arithmetic equations/numerical processing
